trigger:
 branches:
  include:
      - "*"

pool: my-local-pool

name: "$(Date:yyyy-MM-dd) ID $(Rev:.r) [Mirror-To-Git]"

variables:
 - name: git_repo_name
   value: "terrform-showcase"
 - name: branchName
   value: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]

stages:
    - stage: MirrorToGit
      jobs:
          - job:
            displayName: "Mirror To Git"
            steps:
                - checkout: self
                
                - powershell: |
                    $branchName = "$(Build.SourceBranchName)"
                    echo "branch name: $branchName"

                    git checkout -b $branchName

                    git remote remove github
                    git remote add github https://github.com/aravinthk12/$(git_repo_name)

                    git push github $branchName
                    
                  displayName: "Push to GitHub with matching branch name"